library(arules)
library(arulesViz)
groceries<-read.transactions(file.choose(),format = "basket")
inspect(groceries[1:10])
class(groceries)
groceries_rules<-apriori(groceries,parameter = list(support=0.002,confidence=0.05,minlen=3))
inspect(groceries_rules)
plot(groceries_rules)
#########taking support=0.005,confidence=0.02,minlen=5
inspect(groceries[1:10])
class(groceries)
groceries_rules<-apriori(groceries,parameter = list(support=0.001,confidence=0.02,minlen=2))
inspect(groceries_rules)
plot(groceries_rules)
