data()
Q9_a <- read.csv("F:/assignment/Q9_a.csv")
library(e1071)
skewness(Q9_a$speed, Q9_a$dist)
plot(Q9_a$speed, Q9_a$dist)
kurtosis(Q9_a$speed, Q9_a$dist)
hist(Q9_a$speed)
hist(Q9_a$dist)
boxplot(Q9_a$dist)
boxplot(Q9_a$speed)
