data()
Q9_b <-read.csv("F:assignment/Q9_b.csv")
library(e1071)
skewness(Q9_b$SP,Q9_b$WT)
plot(Q9_b$SP, Q9_b$WT)
kurtosis(Q9_b$SP, Q9_b$WT)
plot(Q9_b$SP,Q9_b$WT)
hist(Q9_b$SP)
hist(Q9_b$WT)
boxplot(Q9_b$SP)
boxplot(Q9_b$WT)